GET http://localhost:3000/users

###
GET http://localhost:3000/users/1

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "coppycat@example.com",
  "username": "CoppyCat",
  "password": "123456",
  "rol": "user"
}

###
PUT http://localhost:3000/users/1
Content-Type: application/json

{
  "username": "Juan"
}

###
DELETE http://localhost:3000/users/19

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "achupika@gmail.com",
  "username": "chukapi",
  "password": "123456"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "Antoño",
  "password": "thiago"
}

###
GET http://localhost:3000/categories

###
GET http://localhost:3000/categories/2

###
POST  http://localhost:3000/categories
Content-Type: application/json

{
  "name": "weapons",
  "description": "amazing weapons to fight monsters"
}

###
PUT http://localhost:3000/categories/2
Content-Type: application/json

{
  "name": "armors",
  "description": "strong armors to protect strong heroes!"
}

###
DELETE http://localhost:3000/categories/1