GET http://localhost:3000/users

###
GET http://localhost:3000/users/1

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "puto@gmail.com",
  "username": "mamahuevo",
  "password": "123456",
  "rol": "user"
}

###
PUT http://localhost:3000/users/2
Content-Type: application/json

{
  "username": "CoppyCat"
}

###
DELETE http://localhost:3000/users/2

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "azulcomoelmarazul@gmail.com",
  "username": "WTFunPERUANO",
  "password": "123456"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "Antoño",
  "password": "thiago"
}